// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhtcaxlflfxrqzlhokvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpodGNheGxmbGZ4cnF6bGhva3ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTYwMDMsImV4cCI6MjA2NzA3MjAwM30.pi3_nFCfsQtxZd_7MV0lljd5h0GInNy3p-337zBoD8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});